version: '3.7'
services:
  app:
    build:
      args:
        user: nobody
        uid: 11125
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile
    container_name: vocgame-app
    restart: always
    networks:
      internal:
        ipv4_address: 192.168.29.1
        aliases:
          - app


  nginx:
    image: nginx:alpine
    container_name: vocgame-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/vocgame
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      internal:
        ipv4_address: 192.168.29.2
        aliases:
          - webserver
      
networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.29.0/10"
