version: '3.7'
services:
  app:
    build:
      args:
        user: vocgame
        uid: 11125
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile
    container_name: vocgame-app
    restart: unless-stopped
    working_dir: /var/www/vocgame
    volumes:
      - ./src:/var/www/vocgame
    networks:
      - vocgame

  nginx:
    image: nginx:alpine
    container_name: vocgame-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/vocgame
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vocgame
volumes:
  phpconfig:

networks:
  vocgame:
    driver: bridge
