version: '3.7'
services:
  app:
    build:
      args:
        user: nobody
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile
    container_name: vocgame-app
    restart: always
    networks:
      internal:
        ipv4_address: 192.168.29.1
        aliases:
          - app


  nginx:
    build:
      args:
        user: nginx
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile.webserver
    container_name: vocgame-webserver
    restart: always
    ports:
      - 80:80
    networks:
      internal:
        ipv4_address: 192.168.29.2
        aliases:
          - webserver
      
networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.29.0/10"
