version: '3.9'

services:
  app:
    build:
      args:
        user: nobody
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile.app
    container_name: vocgame-app
    restart: always
    networks:
      internal:
        ipv4_address: 192.168.29.1
        aliases:
          - app
  
  webserver:
    build:
      args:
        user: apache
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile.webserver
    container_name: vocgame-webserver
    restart: always
    networks:
      internal:
        ipv4_address: 192.168.29.2
        aliases:
          - webserver
  
  proxy:
    build:
      args:
        user: nginx
        config_dir: /config
        work_dir: /var/www/vocgame
        src_dir: /src
      context: .
      dockerfile: Dockerfile.proxy
    container_name: vocgame-proxy
    restart: always
    ports:
      - 80:80
    networks:
      internal:
        ipv4_address: 192.168.29.3
        aliases:
          - proxy

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.29.0/10"
